# Generated by Django 2.1.3 on 2018-11-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('referenceurl', models.CharField(max_length=255)),
            ],
        ),
    ]
