# Generated by Django 2.1.3 on 2018-11-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botany',
            fields=[
                ('botany_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_id', models.IntegerField(blank=True, null=True)),
                ('area_easting', models.IntegerField(blank=True, null=True)),
                ('area_northing', models.IntegerField(blank=True, null=True)),
                ('context_number', models.IntegerField(blank=True, null=True)),
                ('sample_number', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_date', models.DateTimeField(auto_now=True)),
                ('analyst', models.CharField(default='', max_length=200)),
                ('notes', models.CharField(default='', max_length=600)),
            ],
            options={
                'verbose_name_plural': 'Botany',
                'db_table': 'samples"."botany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('fraction_id', models.AutoField(primary_key=True, serialize=False)),
                ('proportion_analysed', models.DecimalField(decimal_places=3, max_digits=5)),
                ('soil_volume', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sample_volume', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sample_weight', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Fraction',
                'db_table': 'samples"."fraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FractionComposition',
            fields=[
                ('fract_comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_type', models.CharField(default='', max_length=50)),
                ('fraction', models.CharField(default='', max_length=50)),
                ('type_count', models.DecimalField(decimal_places=4, max_digits=15)),
                ('whole_weight', models.DecimalField(decimal_places=4, max_digits=15)),
                ('fragment_weight', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Composition',
                'db_table': 'samples"."fraction_composition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FractionMaterialsPresent',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Materials Present',
                'db_table': 'samples"."materials_present',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('sample_id', models.IntegerField(blank=True, null=True)),
                ('area_easting', models.IntegerField()),
                ('area_northing', models.IntegerField()),
                ('context_number', models.IntegerField()),
                ('sample_number', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=25)),
                ('specific_material', models.CharField(blank=True, max_length=50, null=True)),
                ('exterior_color_hue', models.CharField(blank=True, max_length=6, null=True)),
                ('exterior_color_lightness_value', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('exterior_color_chroma', models.IntegerField(blank=True, null=True)),
                ('interior_color_hue', models.CharField(blank=True, max_length=6, null=True)),
                ('interior_color_lightness_value', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('interior_color_chroma', models.IntegerField(blank=True, null=True)),
                ('weight_kilograms', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('sample_description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('current_location', models.CharField(max_length=50)),
                ('recovery_type', models.CharField(max_length=25)),
                ('problems', models.CharField(blank=True, max_length=300, null=True)),
                ('image_files', models.CharField(blank=True, max_length=50, null=True)),
                ('number_3d_files', models.CharField(blank=True, db_column='3d_files', max_length=50, null=True)),
                ('chronology', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis_request', models.CharField(blank=True, max_length=50, null=True)),
                ('detailed_sample_description', models.TextField(blank=True, null=True)),
                ('bureaucratic_status', models.CharField(blank=True, max_length=25, null=True)),
                ('subjective_significance', models.NullBooleanField()),
                ('museum_inventory_number', models.IntegerField(blank=True, null=True)),
                ('bureaucratic_status_identifier', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'samples"."samples',
                'managed': False,
            },
        ),
    ]
