# Generated by Django 2.1.3 on 2019-02-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flotation',
            table='kap"."botany',
        ),
        migrations.AlterModelTable(
            name='fraction',
            table='kap"."fraction',
        ),
        migrations.AlterModelTable(
            name='fractioncomposition',
            table='kap"."fraction_composition',
        ),
        migrations.AlterModelTable(
            name='sample',
            table='kap"."sample',
        ),
    ]
