# Generated by Django 2.1.3 on 2019-02-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0002_auto_20190220_1531'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flotation',
            table='kap"."flotation',
        ),
    ]
