# Generated by Django 2.1.3 on 2019-02-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='models3d',
            table='kap"."models3d',
        ),
    ]
