# Generated by Django 2.1.3 on 2019-05-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=200)),
                ('details', models.CharField(default='', max_length=5000)),
                ('category', models.CharField(choices=[('option', 'option'), ('menu change', 'menu change'), ('new form', 'new form'), ('form alteration', 'form alteration'), ('general request', 'general request'), ('other', 'other')], default='', max_length=20)),
                ('system', models.CharField(choices=[('MS Database', 'MS Database'), ('Website', 'Website'), ('GIS', 'GIS'), ('other', 'other')], default='', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('3D Spatial', '3D Spatial'), ('Botany', 'Botany'), ('Ceramics', 'Ceramics'), ('Conservation', 'Conservation'), ('Database', 'Database'), ('Excavation', 'Excavation'), ('Zooarch', 'Zooarchaeology'), ('Other', 'Other')], default='', max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('awaiting assignment', 'awaiting assignment'), ('assigned', 'assigned'), ('next migration', 'next migration'), ('completed', 'completed')], default='awaiting assignment', max_length=20, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Urgent', 'Urgent (Hour)'), ('High', 'High (Day)'), ('Medium', 'Medium (Week)'), ('Low', 'Low (Season)'), ('None', 'None')], default='', max_length=20, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
