# Generated by Django 2.1.3 on 2019-05-07 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('details', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('category', models.CharField(choices=[('option', 'option'), ('other', 'other')], default='', max_length=20)),
                ('department', models.CharField(choices=[('Zooarch', 'Zooarchaeology'), ('other', 'other')], default='', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('awaiting assignment', 'awaiting assignment'), ('assigned', 'assigned'), ('resolved', 'resolved')], default='', max_length=20, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(db_column='taken_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
