# Generated by Django 2.1.3 on 2019-05-06 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignation',
            fields=[
                ('assignation_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_to', models.ForeignKey(db_column='taken_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('details', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('submitted_by', models.ForeignKey(db_column='taken_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignation',
            name='ticket_id',
            field=models.ForeignKey(db_column='ticket_id', on_delete=django.db.models.deletion.PROTECT, to='tickets.Ticket'),
        ),
    ]
