# Generated by Django 2.1.3 on 2019-05-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('option', 'option'), ('other', 'other')], default='', max_length=20),
        ),
    ]
