# Generated by Django 2.1.3 on 2019-05-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('Zooarch', 'Zooarchaeology'), ('other', 'other')], default='', max_length=20),
        ),
    ]
