# Generated by Django 2.1.3 on 2019-05-06 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_ticket_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignation',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='assignation',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(db_column='assigned_to', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='assigned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('awaiting assignment', 'awaiting assignment'), ('assigned', 'assigned'), ('resolved', 'resolved')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Assignation',
        ),
    ]
