# Generated by Django 2.1.3 on 2019-05-06 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190507_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
