# Generated by Django 2.1.3 on 2019-02-22 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('icon_desc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='images/icons/')),
            ],
            options={
                'verbose_name_plural': 'icons',
                'db_table': 'kap"."icon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JoinSampleContainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'kap"."joinsamplecontainer',
                'ordering': ['container_id', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
                ('orderby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'locations',
                'db_table': 'kap"."location',
                'ordering': ['orderby'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(default='', max_length=200)),
                ('address_1', models.CharField(default='', max_length=200)),
                ('address_2', models.CharField(default='', max_length=200)),
                ('region', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('zip', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='Turkey', max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('orderby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'stores',
                'db_table': 'kap"."store',
                'ordering': ['orderby'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False)),
                ('container_name', models.CharField(blank=True, max_length=50, null=True)),
                ('container_type', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_desc', models.ForeignKey(blank=True, db_column='icon_desc', default='Box', null=True, on_delete=django.db.models.deletion.PROTECT, to='depot.Icon')),
                ('location_id', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, to='depot.Location')),
            ],
            options={
                'db_table': 'kap"."container',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_easting', models.IntegerField(choices=[('', ''), (99, 99), (108, 108), (109, 109), (81, 81), (84, 84), (93, 93), (95, 95), (97, 97), (98, 98), (987, 987)])),
                ('area_northing', models.IntegerField(choices=[('', ''), (523, 523), (526, 526), (551, 551), (536, 536), (545, 545), (555, 555), (541, 541), (531, 531), (987, 987)])),
                ('context_number', models.IntegerField()),
                ('sample_number', models.IntegerField()),
                ('sample_type', models.CharField(blank=True, choices=[('', ''), ('Botanical', 'Botanical'), ('Ceramic', 'Ceramic')], default='', max_length=200, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('recovery_method', models.CharField(blank=True, choices=[('', ''), ('Hand', 'Hand')], default='', max_length=200, null=True)),
                ('comments', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('taken_by', models.ForeignKey(db_column='taken_by', on_delete=django.db.models.deletion.PROTECT, related_name='depotsample_taken_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kap"."sample',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='container',
            name='samples',
            field=models.ManyToManyField(to='depot.Sample'),
        ),
    ]
