# Generated by Django 2.1.3 on 2019-02-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, choices=[('', ''), ('Botanical', 'Botanical'), ('Ceramic', 'Ceramic'), ('Organic', 'Organic')], default='', max_length=200, null=True),
        ),
    ]
