# Generated by Django 2.1.3 on 2019-04-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0003_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='container_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='depot.Container'),
        ),
    ]
